<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalHaber</name>
   <tag></tag>
   <elementGuidId>0392b8ab-e0b3-4580-aa8b-9df605226f49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[1]/div/div/div[1]/div/div[97]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[1]/div/div/div[1]/div/div[97]/div</value>
   </webElementXpaths>
</WebElementEntity>
