<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Chk_UsaDistintosConceptosOLeyendas</name>
   <tag></tag>
   <elementGuidId>db7b37e9-3b47-4d5e-b915-ffbf5bec978f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propiedadesAsientoChk13']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='propiedadesAsientoChk13']</value>
   </webElementXpaths>
</WebElementEntity>
