<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonAceptarMonedaOperaEn</name>
   <tag></tag>
   <elementGuidId>fc33acb5-228b-498f-bfe3-e092914deb99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='ContainerPage']/div[2]/div[2]/div[4]/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//body/div[@id='ContainerPage']/div[2]/div[2]/div[4]/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/button[1]</value>
   </webElementXpaths>
</WebElementEntity>
