<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputBuscarMonedaBase</name>
   <tag></tag>
   <elementGuidId>54fa3bda-39ec-4931-8dca-281fed7b4927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchInputPopUpMoneda_Single']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='searchInputPopUpMoneda_Single']</value>
   </webElementXpaths>
</WebElementEntity>
