<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonAceptarPopupResultados</name>
   <tag></tag>
   <elementGuidId>d39d23a4-6d28-49ac-a6fb-b299525299b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;popupResultados&quot;]/div/div[3]/div/div[3]/div/button
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@id=&quot;popupResultados&quot;]/div/div[3]/div/div[3]/div/button</value>
   </webElementXpaths>
</WebElementEntity>
