<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonUltimoDato</name>
   <tag></tag>
   <elementGuidId>6f268265-baad-437d-85b8-758501b97474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[contains(text(),'last_page')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//i[contains(text(),'last_page')]</value>
   </webElementXpaths>
</WebElementEntity>
