<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonCerrarPopupIntegrarModeloAsientos</name>
   <tag></tag>
   <elementGuidId>50a18495-1f96-466a-8032-8e2e9afbc7ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='ContainerPage']/div[2]/div[4]/div[18]/div[1]/div[1]/div[1]/div[2]/button[1]/i[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//body/div[@id='ContainerPage']/div[2]/div[4]/div[18]/div[1]/div[1]/div[1]/div[2]/button[1]/i[1]</value>
   </webElementXpaths>
</WebElementEntity>
