<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonNOPopupTerminarAsiento</name>
   <tag></tag>
   <elementGuidId>3b268709-5c6d-4548-b656-18379fcfa32a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='modalConfirmacionAsientos']/div[1]/div[1]/div[3]/div[1]/div[1]/div[3]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//body/div[@id='modalConfirmacionAsientos']/div[1]/div[1]/div[3]/div[1]/div[1]/div[3]/button[1]</value>
   </webElementXpaths>
</WebElementEntity>
