<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DDOrdenadoPor</name>
   <tag></tag>
   <elementGuidId>b34b7cd0-0c4c-4b1b-bf68-0a856a285750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select_popupSeleccionMes_Orden']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//select[@id='select_popupSeleccionMes_Orden']</value>
   </webElementXpaths>
</WebElementEntity>
