<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LabelTituloPopupAsientos</name>
   <tag></tag>
   <elementGuidId>2d8beaab-7fe1-4c97-9967-6ed5d040142e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='ContainerPage']/div[2]/div[3]/div[1]/div[1]/div[1]/div[1]/label[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//body/div[@id='ContainerPage']/div[2]/div[3]/div[1]/div[1]/div[1]/div[1]/label[1]</value>
   </webElementXpaths>
</WebElementEntity>
