<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonAceptarPopupCierreyApertura</name>
   <tag></tag>
   <elementGuidId>262d508a-95c4-4231-9260-875fb519b899</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@onclick,'CargarResultados(this);')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[contains(@onclick,'CargarResultados(this);')]</value>
   </webElementXpaths>
</WebElementEntity>
