<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputCuentaResultadodelEjercicio</name>
   <tag></tag>
   <elementGuidId>6b4f1bcb-9dcf-4f6c-9294-b029d08df328</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cuentaResultadoEjercicio']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='cuentaResultadoEjercicio']</value>
   </webElementXpaths>
</WebElementEntity>
