<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputCuentaResultadosAcumulados</name>
   <tag></tag>
   <elementGuidId>2c0a1a41-56cf-4dcf-bb69-c92fcc0a69b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'cuentaResultadoEjercicioAcumulado')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[contains(@id,'cuentaResultadoEjercicioAcumulado')]</value>
   </webElementXpaths>
</WebElementEntity>
