<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputCotizacion</name>
   <tag></tag>
   <elementGuidId>c389c160-d01b-4636-b1ec-9198dd1c6113</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='popup-Dif-Cambio-Cotizacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='popup-Dif-Cambio-Cotizacion']</value>
   </webElementXpaths>
</WebElementEntity>
