<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MensajeDeNoGerenacionDiferenciaCambio</name>
   <tag></tag>
   <elementGuidId>226773a3-257a-4f12-a3b0-7328fa6b740f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='ContainerPage']/div[@id='popUpAvisoMensaje']/div[@id='popUpModalMensajeBody']/div[1]/div[2]/div[1]/div[1]/div[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//body/div[@id='ContainerPage']/div[@id='popUpAvisoMensaje']/div[@id='popUpModalMensajeBody']/div[1]/div[2]/div[1]/div[1]/div[1]/span[1]</value>
   </webElementXpaths>
</WebElementEntity>
