<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DropDown</description>
   <name>DDApertura</name>
   <tag></tag>
   <elementGuidId>e08d4d29-fd0c-4875-9d20-dc094c128f00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='popup-diario-apertura']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//select[@id='popup-diario-apertura']</value>
   </webElementXpaths>
</WebElementEntity>
