<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DropDown</description>
   <name>DDMonedaDos</name>
   <tag></tag>
   <elementGuidId>9a9ecffc-2aa7-4d56-9a35-ddd7223e29f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='ContainerPage']/div[2]/div[4]/div[1]/div[1]/div[1]/div[2]/form[1]/div[4]/div[2]/select[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//body/div[@id='ContainerPage']/div[2]/div[4]/div[1]/div[1]/div[1]/div[2]/form[1]/div[4]/div[2]/select[2]</value>
   </webElementXpaths>
</WebElementEntity>
