<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DropDown</description>
   <name>DDOrden</name>
   <tag></tag>
   <elementGuidId>494d1fb0-a2a8-4081-bf63-5066be2ec8cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='popup-diario-orden']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//select[@id='popup-diario-orden']</value>
   </webElementXpaths>
</WebElementEntity>
