<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DropDown</description>
   <name>DDTipoDiario</name>
   <tag></tag>
   <elementGuidId>f61564f7-9d12-4bcb-acd9-93f3d5dc1877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='popup-diario-tipoDiario']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//select[@id='popup-diario-tipoDiario']</value>
   </webElementXpaths>
</WebElementEntity>
