<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonExportarMonedas</name>
   <tag></tag>
   <elementGuidId>abca50e8-53bf-4d18-98f0-46928a3d5581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@class='material-icons'][contains(.,'save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//i[@class='material-icons'][contains(.,'save')]</value>
   </webElementXpaths>
</WebElementEntity>
