<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonPrimerRegistro</name>
   <tag></tag>
   <elementGuidId>2f08d1b2-53cf-4c7a-b383-ebbda1ce2ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@class='material-icons'][contains(.,'first_page')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//i[@class='material-icons'][contains(.,'first_page')]</value>
   </webElementXpaths>
</WebElementEntity>
