<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonAnteriorRegistro</name>
   <tag></tag>
   <elementGuidId>79509cc0-6e1f-4d82-8376-83b713e2ea0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@class='material-icons'][contains(.,'chevron_left')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//i[@class='material-icons'][contains(.,'chevron_left')]</value>
   </webElementXpaths>
</WebElementEntity>
