<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonSiguienteRegistro</name>
   <tag></tag>
   <elementGuidId>513495ec-17bf-45e4-b4a4-ac22c48385a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@class='material-icons'][contains(.,'chevron_right')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//i[@class='material-icons'][contains(.,'chevron_right')]</value>
   </webElementXpaths>
</WebElementEntity>
