<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonExportarMonedasWord</name>
   <tag></tag>
   <elementGuidId>88986276-bcbc-476d-92bc-34e9c2cbedbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='dropdown-item'][contains(.,'Word')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//a[@class='dropdown-item'][contains(.,'Word')]</value>
   </webElementXpaths>
</WebElementEntity>
