<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalCreditos</name>
   <tag></tag>
   <elementGuidId>194e9c8d-6542-4d4a-89f4-d96fe23ee421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[1]/div/div/div[1]/div/div[86]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[3]/div[1]/div/div/div[1]/div/div[86]/div</value>
   </webElementXpaths>
</WebElementEntity>
