<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PasivoMasPatrimonio</name>
   <tag></tag>
   <elementGuidId>39d66373-b11b-41ba-847b-a01773faa8e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[1]/div/div/div[1]/div/div[40]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[3]/div[1]/div/div/div[1]/div/div[40]/div</value>
   </webElementXpaths>
</WebElementEntity>
