<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sub-TabAsientos</name>
   <tag></tag>
   <elementGuidId>8d3fa825-cfd4-4ee9-9baa-3f8ec6ac3060</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='ContainerPage']/div[@id='menu_topToggle']/div[1]/div[2]/div[2]/div[1]/div[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//body/div[@id='ContainerPage']/div[@id='menu_topToggle']/div[1]/div[2]/div[2]/div[1]/div[1]/a[1]</value>
   </webElementXpaths>
</WebElementEntity>
