<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sub-TabAsientosAutomaticosCierreApertura</name>
   <tag></tag>
   <elementGuidId>c7a1f590-bb6f-4cda-87b0-acecf13b3b1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='v-pills-cierreYApertura-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//a[@id='v-pills-cierreYApertura-tab']</value>
   </webElementXpaths>
</WebElementEntity>
