<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sub-TabGrupoDeCuentas</name>
   <tag></tag>
   <elementGuidId>55381c28-1625-488e-a27d-7f6fdfb49801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='v-pills-gruposDeCuentas-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//a[@id='v-pills-gruposDeCuentas-tab']</value>
   </webElementXpaths>
</WebElementEntity>
