<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonAceptarPopupClientesProveedores</name>
   <tag></tag>
   <elementGuidId>83eb07a1-c1f9-4db4-b2be-3064ffd26738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='ContainerPage']/div[2]/div[5]/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//body/div[@id='ContainerPage']/div[2]/div[5]/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/button[1]</value>
   </webElementXpaths>
</WebElementEntity>
