<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonListadoRUT</name>
   <tag></tag>
   <elementGuidId>b7aa467c-6e97-46ea-87dc-50cab7a1931a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='ContainerPage']/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/a[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//body/div[@id='ContainerPage']/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/a[1]/span[1]</value>
   </webElementXpaths>
</WebElementEntity>
