<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DropDown</description>
   <name>DDApertura</name>
   <tag></tag>
   <elementGuidId>4f7cacd8-0ad5-40b8-b032-16ba80cc4f8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='popup-reporte-apertura']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//select[@id='popup-reporte-apertura']</value>
   </webElementXpaths>
</WebElementEntity>
