<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DropDown</description>
   <name>DDLibro</name>
   <tag></tag>
   <elementGuidId>235dbc9e-de9a-42fb-ad43-6e890f20070a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='popup-susidiarios-ModoLibro']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//select[@id='popup-susidiarios-ModoLibro']</value>
   </webElementXpaths>
</WebElementEntity>
