<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Dolares</description>
   <name>LabelTituloReporteLB-D</name>
   <tag></tag>
   <elementGuidId>59f6b2d2-cf17-48de-9a09-e6b9f89c1fa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;reportViewer1&quot;]/div/div[2]/div[2]/div[1]/div[3]/div[1]/div/div/div[1]/div/div[89]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;reportViewer1&quot;]/div/div[2]/div[2]/div[1]/div[3]/div[1]/div/div/div[1]/div/div[89]/div</value>
   </webElementXpaths>
</WebElementEntity>
